import {store} from 'shared/store';
import {RF, WP} from './responsive';
import {DefaultTheme} from '@react-navigation/native';

const AppTheme = {
  COLORS: {
    primaryBackground: '#FFFFFF',
    primaryDarkBackground: '#000000',
    // primaryLightBackground: '#F2F5FF',
    primaryBlueBg: '#16275A',
    primaryGreenBg: '#16275A',
    secondaryBackground: 'rgba(202, 202, 202, 0.1)',
    // secondaryDarkBackground: '#393939',
    // secondaryBlueBackground: '#003075',
    greyLight: '#CACACA',
    greyDark: '#999999', //text
    secondaryGreyBackground: 'rgba(201, 206, 219, 0.42)',
    secondaryGreyLightBg: '#F5F5F5',
    changeGreen: '#00C053',
    changeRed: '#ff3939',
    yellow: '#E4B40E',
    text: '#000',
    purple: '#6829E1',
    accentBlue: '#27A3E3',
    lightBlue: '#209EE2',
    textLight: '#928FA3',
    disabledTextLight: '#7f7e83',
    textExtraLight: 'rgba(146, 143, 163, 0.5)',
    green: '#1CD983',
    blue: '#4C7BF6',
    red: '#FF0000',
    countRed: '#FD6969',
    gold: '#F89F36',
    white: '#fff',
    black: '#000',
    lightGrey: '#7F819A',
    gradientTopColor: '#3e68df',
    gradientBottomColor: '#178ee8',
    // dottedBorder: '#20FFFF',
    // tabColor: '#131C3F',
    // chartColor: '#5E93E3',
    // biometryCircleButtonColor: '#414A5B',
    // reddishBackground: '#e6d7d7',
  },
  FONTS: {
    // SIZE: {
    //   XXLARGE: RF(32),
    //   XLARGE: RF(24),
    //   LARGE: RF(20),
    //   MEDIUM: RF(18),
    //   SMALL: RF(16),
    //   XSMALL: RF(14),
    //   XXSMALL: RF(12),
    //   XXXSMALL: RF(10),
    //   XXXXSMALL: RF(8),
    // },
    TYPE: {
      LIGHT: 'Montserrat-Light',
      REGULAR: 'Montserrat-Regular',
      MEDIUM: 'Montserrat-Medium',
      SEMIBOLD: 'Montserrat-SemiBold',
      BOLD: 'Montserrat-Bold',
    },
  },
  // MARGIN: {
  //   SUPER_LOW: RF(2),
  //   VERY_LOW: RF(4),
  //   LOW: RF(8),
  //   MID_LOW: RF(12),
  //   NORMAL: RF(16),
  //   HIGH: RF(24),
  //   VERY_HIGH: RF(32),
  //   SUPER_HIGH: RF(48),
  //   NOVA_HIGH: RF(60),
  // },
  // PADDING: {
  //   SUPER_LOW: RF(2),
  //   VERY_LOW: RF(4),
  //   LOW: RF(8),
  //   MID_LOW: RF(12),
  //   NORMAL: RF(16),
  //   HIGH: RF(24),
  //   VERY_HIGH: RF(32),
  //   SUPER_HIGH: RF(48),
  // },
  // RADIUS: {
  //   BOX: RF(10),
  //   SMALL_BOX: RF(5),
  //   OVAL: RF(24),
  // },
  // SIZE: {
  //   BOTTOM: 0,
  //   BUTTON_WIDTH: WP(85),
  //   ROOT_WIDTH: WP(100) - RF(24),
  //   HEADER_BACK: RF(22),
  //   BUTTON_HEIGHT: RF(55),
  //   QR: RF(100),
  //   SMALL_BUTTON_HEIGHT: RF(35),
  //   FULL_WIDTH: WP(100),
  //   INTRO_IMAGE: RF(180),
  //   APP_LOGO: RF(170),
  //   ICON: RF(15),
  //   ICON_MEDIUM: RF(18),
  //   ICON_LARGE: RF(30),
  //   ICON_XLARGE: RF(50),
  //   COIN_ICON: RF(50),
  //   PIN_INPUT: {
  //     height: RF(60),
  //     width: RF(40),
  //   },
  // },
};

export {AppTheme};
